### ISSUE TITLE
AttributeError: 'Terminal' object has no attribute 'get_scrollback_lines'

### ISSUE THREAD

**Issue by quozl** [sugarlabs/terminal-activity#37]
Clear scrollback does not work, and logs contain;

```log
Traceback (most recent call last):
  File "/home/olpc/Activities/Terminal.activity/terminal.py", line 669, in __clear_cb
    n = vt.get_scrollback_lines()
AttributeError: 'Terminal' object has no attribute 'get_scrollback_lines'
```

Regression introduced in https://github.com/sugarlabs/terminal-activity/pull/33 and https://github.com/sugarlabs/terminal-activity/commit/f5b5e73fc874c85f20ce1c9a8d8c76279e40c450.

**Comment by chimosky** [comment]
Reproduced but no output in log.

**Comment by quozl** [comment]
Are you using Python 3?  No output is visible when using Python 3 until the activity is stopped.  The _logging_ module has changed behaviour between Python 2 and Python 3 with respect to flushing output.  It makes the Log activity less useful.

**Comment by chimosky** [comment]
> Are you using Python 3?

Yes but this is all the log outputs.
```
(sugar-activity3:960): Vte-WARNING **: 10:58:42.299: VteSelectionFunc callback ignored.

Normal successful completion, pid 960 activity_id c5f4df6646b653c1a6ab0790bb9f41077d87b4ba
```

**Comment by quozl** [comment]
Yes, subject to differences in line numbers, times, pid, and hashes, I see the same log output you do when I test on one system.  And the _Clear scrollback_ button does work.  The scrollback is cleared.

However, on another system, the _Clear scrollback_ button does not clear the scrollback, and the log contains the _AttributeError: 'Terminal' object has no attribute 'get_scrollback_lines'_ message.

**Comment by chimosky** [comment]
> Yes, subject to differences in line numbers, times, pid, and hashes, I see the same log output you do when I test on one system. And the _Clear scrollback_ button does work. The scrollback is cleared.
> 
> However, on another system, the _Clear scrollback_ button does not clear the scrollback, and the log contains the _AttributeError: 'Terminal' object has no attribute 'get_scrollback_lines'_ message.

Testing with HEAD at the commit where the change was made in 0.114, the _Clear scrollback_ button doesn't work and the log contains the error.

**Comment by quozl** [comment]
Thanks.  On the same systems, please test this reproducer;

```bash
python -c 'from gi.repository import Vte;print(Vte.Terminal.get_scrollback_lines)'
```

@Hrishi1999, you were involved in the original pull request, do you have any comments?

**Comment by quozl** [comment]
Never mind, I've fixed it.
