### PR TITLE
Fix theme not switching to dark on toggle

### LINKED ISSUE #45: shift+ctrl+i stopped working
As at 4274006, when the dark mode is the default on startup, pressing shift+ctrl+i to change it is initially ineffective; one has to press it again.

### PR DESCRIPTION
**Pull request by shaansubbaiah**
The way the custom colors have been implemented is such that any theme
 chosen- light/dark/custom overrides the custom colors defined. So after
 using the dark theme, closing, and opening again the theme is actually
 'custom' but with the dark colors applied.
Pressing <shift><ctrl><I> toggles it to dark mode (from custom) and
then to light mode (from dark) on the second try.

The fix i toggles to light if the custom colors match the dark colors (or)
 icon is 'light-theme'.

Regression introduced in 4274006

Fixes #45

### CODE REVIEW

**Comment by shaansubbaiah** [comment]
Following this workflow:
Open Terminal -> Toggle to dark theme -> Close -> Open Terminal -> Dark theme and **Toggle button is 'dark-theme'**

The problem is that the toggle button label is set to 'dark-theme' during creation, and I can't figure out how to read the custom theme colors to change the label on startup.

I have tried something along the lines of 
```python
vt = self._notebook.get_nth_page(0).vt
logging.debug(vt.get_custom_colors_dict())
```
Resulting in
```python
AttributeError: 'SugarTerminal' object has no attribute '_color_to_list'
```

@srevinsaju kindly tell me what I'm doing wrong?

**Comment by srevinsaju** [comment]
`logging.debug(vt.get_custom_colors_dict())` does not give the custom colors,
 `TerminalActivity._theme_colors.get('custom')` is the one which should give the custom theme's preferences

**Comment by srevinsaju** [comment]
I can try to explain how it works, in short

`Vte` terminal instance is defined in `sugarterm.py`. `SugarTerminal` is only a terminal instance which supports setting custom colors, and supports highlighting URLs. The `SugarTerminal` exposes a public method which allows the Activity instance to set colors on the `Vte` instance using `vt.set_term_colors`, 

The `SugarTerminal.set_term_colors` accepts a dictionary like parameter, which provides `fg_color` and `bg_color`, the `SugarTerminal` instance parses the color and updates the Terminal instance's colors with the new terminal colors. Also, to note, this only changes the color of the only terminal instance of which the method was called. 

To understand this better, consider the `Konsole` or `Gnome Terminal`

The `terminal.py` makes the user accessible features like User Interface and setting custom themes, increasing the size of font, adding new tabs, etc

When we press the `Add New Tab` button, a new instance of `SugarTerminal` (which is a Virtual Terminal <=> `Vte`) is created. The `terminal.py` tells the object in `sugarterm.py` about which colors to set, and what should be the font size. The `Vte` provides methods for the `terminal.py` to make changes to it. `sugarterm.py` alone does not do anything. All the functions are called from the `terminal.py`, 

Now, about colors

The colors are always set to `custom`. This is the tricky part

When `self._update_theme` is called, the `terminal.py` iterates through all the tabs and sets the 
```json
"custom": {
   "fg_color": "#000000",
   "bg_color": "#FFFFFF"
 }
```
`.custom.fg_color` and `.custom.bg_color` as the foreground and background color respectively. On load, the Terminal instance looks for the configuration. If the theme is light, the `custom` is automatically redefined to 
```json
"custom": {
   "fg_color": "#000000",
   "bg_color": "#FFFFFF"
 }
```

if the theme preference was dark, the `custom` theme is automatically redefined to 
```json
"custom": {
   "fg_color": "#FFFFFF",
   "bg_color": "#000000"
 }
```

if the theme preference is changed, to something like red or blue, the `custom` is changed again with respective values. In this scenario, the `light`, `dark` keys in the dictionary does not have any significance. They are dummy keys, so that when the `Set Light Theme` or `Set Dark Theme` is pressed, the `custom` key of the dictionary can take the values of `light` or `dark` theme respectively.

https://github.com/sugarlabs/terminal-activity/blame/master/terminal.py#L226 as of the latest commit shows that. 

Let me know if you need more explanation. I too got confused of how `Vte` works, and what I have told above, is afaik since `January`, it should be mostly correct, :smile: 

Also `get_custom_colors_dict` seems like a redundant function I added during GCI, my bad. Thanks for noticing, and sorry for taking your time

**Comment by shaansubbaiah** [comment]
@srevinsaju Thank you for the explanation. I had figured out how the colors work but didn't know when the Terminal read the colors from the datastore. Your previous comment helped find a simpler solution by modifying `update_theme()`.

@quozl @chimosky and @srevinsaju kindly review the fix.

**Comment by shaansubbaiah** [comment]
> I can try to explain how it works, in short
> .
> .
> .
> Also `get_custom_colors_dict` seems like a redundant function I added during GCI, my bad. Thanks for noticing, and sorry for taking your time

A permalink to this explanation should probably be saved somewhere, it will be useful to other contributors

**Comment by quozl** [comment]
Thanks.  Tested.  Merged by hand as ce0f91a.
